Routes.Web/Controllers/HomeController.cs
using Routes.Dal.Entities;
using Routes.Dal.Interfaces;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Routes.Web.Controllers
{
    public class HomeController : Controller
    {
        IRouteRepository repository;

        public HomeController(IRouteRepository repos)
        {
            repository = repos;
        }

        public ActionResult Index()
        {
            return View(repository.GetAll().ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Routes.Web/Controllers/RouteController.cs
using Routes.Dal.Entities;
using Routes.Dal.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace Routes.Web.Controllers
{
    public class RouteController : Controller
    {
        IRouteRepository repository;

        public RouteController(IRouteRepository repo)
        {
            repository = repo;
        }

        // GET: Route
        public ActionResult ShowRoute(int Id)
        {
            return View(repository.GetById(Id));
        }

        public JsonResult GetMarkers(int Id)
        {
            List<RoutesMarker> markers = repository.GetRouteMarkers(Id).ToList();
            return Json(markers,JsonRequestBehavior.AllowGet);
        }

        //Edit
        [HttpGet]
        public ActionResult EditRoute(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Route route = repository.GetById((int)id);

            if (route != null)
            {
                return View(route);
            }
            return HttpNotFound();
        }

        //Create route simple
        [HttpGet]
        public ActionResult CreateRoute()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateRoute(Route route)
        {
            route.RouteEnterTupe = "Simple";
            repository.Create(route);

            return RedirectToAction("Index","Home");
        }

        //Create route manually
        [HttpGet]
        public ActionResult CreateRouteManually()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateRouteManually(Route route)
        {
            repository.Create(route);

            return RedirectToAction("Index");
        }

        public async Task<FileContentResult> GetImage(int routeId,int markerNumber)
        {
            int photoId = repository.GetFirstPhotoId(routeId, markerNumber);

            Photo ph = await repository.GetPhotoAsync(photoId);

            if (ph != null && ph.Image != null)
                return File(ph.Image, ph.MimeType);
            return null;
        }
    }
}

Routes.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Routes.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Routes.Web/Views/Home/Index.cshtml
@model IEnumerable<Routes.Dal.Entities.Route>

@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("Создать простой маршрут","CreateRoute","Route")
<h1>
    Сохраненные маршруты
</h1>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RouteEnterTupe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OriginPoint)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationPoint)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RouteEnterTupe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TravelType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OriginPoint)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinationPoint)
        </td>
        <td>
            @Html.ActionLink("Посмотреть маршрут", "ShowRoute","Route", new { id=item.RouteID },null)
           
        </td>
    </tr>
}

</table>